### ISSUE TITLE
Better newline support

### ISSUE THREAD

**Issue by girasquid** [gmalette/profound#1]
When you add a newline to the message that you want to put into the image, it gets correctly handled and splits the line - but cut off:

![two-liner](https://cloud.githubusercontent.com/assets/60324/5857776/35ec76ae-a21c-11e4-96b0-a5bc0c66cca0.jpg)

I created this using `profound "A two\n liner" ~/Desktop/two-liner.jpg`.

**Comment by gmalette** [comment]
Hahahaha you still use this? I guess I'll have to fix this, I've had issues with it too

**Comment by girasquid** [comment]
Every. Day.

**Comment by gmalette** [comment]
Fixed by 80560f889d67c242bd5e964a290919468bbccf8e, although multiline will be slower than single line. I should review the whole image transformation pipeline lol

**Comment by girasquid** [comment]
:heart_eyes:

**Comment by girasquid** [comment]
![best](https://cloud.githubusercontent.com/assets/60324/5861435/3c4cd8a2-a237-11e4-8693-a13e7f6661b4.jpg)
